    kind: pipeline
    name: default

    steps:
    - name: publish-latest
      image: plugins/docker
      when:
        event: push
        branch: master
      settings:
        repo: jasonraimondi/url-to-png
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
        tags: [ "latest" ]
        force_tag: true
        custom_dns: [ 10.0.0.1, 1.1.1.1 ]

    - name: publish-tag
      image: plugins/docker
      when:
        event:
          - tag
      settings:
        repo: jasonraimondi/url-to-png
        username:
          from_secret: docker_username
        password:
          from_secret: docker_password
        tags: ["latest", $DRONE_TAG]
        auto_tag: true
        force_tag: true
        custom_dns: [ 10.0.0.1, 1.1.1.1 ]
